import Footer from "@/Components/Footer/Footer";
import Header from "@/Components/Header/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css-scss/index.scss";
import EditContextWrapper from "@/Components/Common/EditContextWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EditContextWrapper>
          <>
            <Header />
            <div className="page-main-content">{children}</div>
            <Footer />
          </>
        </EditContextWrapper>
      </body>
    </html>
  );
}
